# mhart/alpine-node:0.10.48 27 mb
# node:12.12.0-alpine
FROM node:alpine as clone 

WORKDIR /app

RUN apk update && apk add git 

RUN git clone https://github.com/mwangiKibui/node.js-rest-api-documentation.git clone 

WORKDIR /app/clone 

RUN npm i 

FROM node:12.12.0-alpine as prod

WORKDIR /app

COPY --from=clone /app/clone . 

CMD ["npm", "start"]