FROM node:alpine

WORKDIR /app

RUN apk update && apk add git curl gzip zip vim jq

RUN git clone https://github.com/mwangiKibui/node.js-rest-api-documentation.git clone 

WORKDIR /app/clone 

RUN npm i 

RUN npm build

CMD [ "npm",  "start" ]

